services:
  - type: web
    name: rag-chatbot-app
    runtime: docker
    plan: free
    port: 8000

    envVars:
      - key: SUPABASE_DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
